// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: user.proto

#include "user.pb.h"
#include "user.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace fixbug {

static const char* UserServiceRpc_method_names[] = {
  "/fixbug.UserServiceRpc/Login",
};

std::unique_ptr< UserServiceRpc::Stub> UserServiceRpc::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< UserServiceRpc::Stub> stub(new UserServiceRpc::Stub(channel, options));
  return stub;
}

UserServiceRpc::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Login_(UserServiceRpc_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status UserServiceRpc::Stub::Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::fixbug::LoginResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fixbug::LoginRequest, ::fixbug::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Login_, context, request, response);
}

void UserServiceRpc::Stub::async::Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fixbug::LoginRequest, ::fixbug::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, std::move(f));
}

void UserServiceRpc::Stub::async::Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Login_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>* UserServiceRpc::Stub::PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fixbug::LoginResponse, ::fixbug::LoginRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Login_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>* UserServiceRpc::Stub::AsyncLoginRaw(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLoginRaw(context, request, cq);
  result->StartCall();
  return result;
}

UserServiceRpc::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      UserServiceRpc_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< UserServiceRpc::Service, ::fixbug::LoginRequest, ::fixbug::LoginResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](UserServiceRpc::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fixbug::LoginRequest* req,
             ::fixbug::LoginResponse* resp) {
               return service->Login(ctx, req, resp);
             }, this)));
}

UserServiceRpc::Service::~Service() {
}

::grpc::Status UserServiceRpc::Service::Login(::grpc::ServerContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fixbug
#include <grpcpp/ports_undef.inc>

