// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: test.proto
#ifndef GRPC_test_2eproto__INCLUDED
#define GRPC_test_2eproto__INCLUDED

#include "test.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace fixbug {

// UserServiceRpc 提供用户相关的 RPC 服务
// 包括用户登录、注册、信息查询等功能
class UserServiceRpc final {
 public:
  static constexpr char const* service_full_name() {
    return "fixbug.UserServiceRpc";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // 用户登录验证
    // 接收登录请求，验证用户名和密码，返回登录结果
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::fixbug::LoginResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    // 获取好友列表
    // 响应
    virtual ::grpc::Status GetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::fixbug::GetFriendListResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendListResponse>> AsyncGetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendListResponse>>(AsyncGetFriendListsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendListResponse>> PrepareAsyncGetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendListResponse>>(PrepareAsyncGetFriendListsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // 用户登录验证
      // 接收登录请求，验证用户名和密码，返回登录结果
      virtual void Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // 获取好友列表
      // 响应
      virtual void GetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest* request, ::fixbug::GetFriendListResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest* request, ::fixbug::GetFriendListResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendListResponse>* AsyncGetFriendListsRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fixbug::GetFriendListResponse>* PrepareAsyncGetFriendListsRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::fixbug::LoginResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    ::grpc::Status GetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::fixbug::GetFriendListResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendListResponse>> AsyncGetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendListResponse>>(AsyncGetFriendListsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendListResponse>> PrepareAsyncGetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendListResponse>>(PrepareAsyncGetFriendListsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response, std::function<void(::grpc::Status)>) override;
      void Login(::grpc::ClientContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest* request, ::fixbug::GetFriendListResponse* response, std::function<void(::grpc::Status)>) override;
      void GetFriendLists(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest* request, ::fixbug::GetFriendListResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fixbug::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::fixbug::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendListResponse>* AsyncGetFriendListsRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fixbug::GetFriendListResponse>* PrepareAsyncGetFriendListsRaw(::grpc::ClientContext* context, const ::fixbug::GetFriendListRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
    const ::grpc::internal::RpcMethod rpcmethod_GetFriendLists_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // 用户登录验证
    // 接收登录请求，验证用户名和密码，返回登录结果
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response);
    // 获取好友列表
    // 响应
    virtual ::grpc::Status GetFriendLists(::grpc::ServerContext* context, const ::fixbug::GetFriendListRequest* request, ::fixbug::GetFriendListResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::fixbug::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::fixbug::LoginResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetFriendLists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetFriendLists() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetFriendLists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendLists(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFriendLists(::grpc::ServerContext* context, ::fixbug::GetFriendListRequest* request, ::grpc::ServerAsyncResponseWriter< ::fixbug::GetFriendListResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Login<WithAsyncMethod_GetFriendLists<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Login() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::fixbug::LoginRequest, ::fixbug::LoginResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fixbug::LoginRequest* request, ::fixbug::LoginResponse* response) { return this->Login(context, request, response); }));}
    void SetMessageAllocatorFor_Login(
        ::grpc::MessageAllocator< ::fixbug::LoginRequest, ::fixbug::LoginResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fixbug::LoginRequest, ::fixbug::LoginResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetFriendLists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetFriendLists() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::fixbug::GetFriendListRequest, ::fixbug::GetFriendListResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fixbug::GetFriendListRequest* request, ::fixbug::GetFriendListResponse* response) { return this->GetFriendLists(context, request, response); }));}
    void SetMessageAllocatorFor_GetFriendLists(
        ::grpc::MessageAllocator< ::fixbug::GetFriendListRequest, ::fixbug::GetFriendListResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fixbug::GetFriendListRequest, ::fixbug::GetFriendListResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetFriendLists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendLists(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFriendLists(
      ::grpc::CallbackServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Login<WithCallbackMethod_GetFriendLists<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetFriendLists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetFriendLists() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetFriendLists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendLists(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Login() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetFriendLists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetFriendLists() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetFriendLists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendLists(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetFriendLists(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Login() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Login(context, request, response); }));
    }
    ~WithRawCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetFriendLists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetFriendLists() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetFriendLists(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetFriendLists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetFriendLists(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetFriendLists(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fixbug::LoginRequest, ::fixbug::LoginResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fixbug::LoginRequest, ::fixbug::LoginResponse>* streamer) {
                       return this->StreamedLogin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::fixbug::LoginRequest* /*request*/, ::fixbug::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fixbug::LoginRequest,::fixbug::LoginResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetFriendLists : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetFriendLists() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fixbug::GetFriendListRequest, ::fixbug::GetFriendListResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fixbug::GetFriendListRequest, ::fixbug::GetFriendListResponse>* streamer) {
                       return this->StreamedGetFriendLists(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetFriendLists() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetFriendLists(::grpc::ServerContext* /*context*/, const ::fixbug::GetFriendListRequest* /*request*/, ::fixbug::GetFriendListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetFriendLists(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fixbug::GetFriendListRequest,::fixbug::GetFriendListResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_GetFriendLists<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Login<WithStreamedUnaryMethod_GetFriendLists<Service > > StreamedService;
};

}  // namespace fixbug


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_test_2eproto__INCLUDED
